//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServicesTest.CustomersWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="customers", Namespace="http://schemas.datacontract.org/2004/07/wcf_fullcarwash")]
    [System.SerializableAttribute()]
    public partial class customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numberdniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthdate {
            get {
                return this.birthdateField;
            }
            set {
                if ((this.birthdateField.Equals(value) != true)) {
                    this.birthdateField = value;
                    this.RaisePropertyChanged("birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullnameField, value) != true)) {
                    this.fullnameField = value;
                    this.RaisePropertyChanged("fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numberdni {
            get {
                return this.numberdniField;
            }
            set {
                if ((object.ReferenceEquals(this.numberdniField, value) != true)) {
                    this.numberdniField = value;
                    this.RaisePropertyChanged("numberdni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomersWS.IServiceCustomer")]
    public interface IServiceCustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/getcustomers", ReplyAction="http://tempuri.org/IServiceCustomer/getcustomersResponse")]
        WCFServicesTest.CustomersWS.customers[] getcustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/getcustomers", ReplyAction="http://tempuri.org/IServiceCustomer/getcustomersResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.CustomersWS.customers[]> getcustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/insertcustomer", ReplyAction="http://tempuri.org/IServiceCustomer/insertcustomerResponse")]
        bool insertcustomer(WCFServicesTest.CustomersWS.customers objcustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/insertcustomer", ReplyAction="http://tempuri.org/IServiceCustomer/insertcustomerResponse")]
        System.Threading.Tasks.Task<bool> insertcustomerAsync(WCFServicesTest.CustomersWS.customers objcustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/updatecustomer", ReplyAction="http://tempuri.org/IServiceCustomer/updatecustomerResponse")]
        bool updatecustomer(WCFServicesTest.CustomersWS.customers objcustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/updatecustomer", ReplyAction="http://tempuri.org/IServiceCustomer/updatecustomerResponse")]
        System.Threading.Tasks.Task<bool> updatecustomerAsync(WCFServicesTest.CustomersWS.customers objcustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/deletecustomer", ReplyAction="http://tempuri.org/IServiceCustomer/deletecustomerResponse")]
        bool deletecustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/deletecustomer", ReplyAction="http://tempuri.org/IServiceCustomer/deletecustomerResponse")]
        System.Threading.Tasks.Task<bool> deletecustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/getcustomerById", ReplyAction="http://tempuri.org/IServiceCustomer/getcustomerByIdResponse")]
        WCFServicesTest.CustomersWS.customers getcustomerById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/getcustomerById", ReplyAction="http://tempuri.org/IServiceCustomer/getcustomerByIdResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.CustomersWS.customers> getcustomerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/getcustomerLogin", ReplyAction="http://tempuri.org/IServiceCustomer/getcustomerLoginResponse")]
        WCFServicesTest.CustomersWS.customers getcustomerLogin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/getcustomerLogin", ReplyAction="http://tempuri.org/IServiceCustomer/getcustomerLoginResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.CustomersWS.customers> getcustomerLoginAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCustomerChannel : WCFServicesTest.CustomersWS.IServiceCustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCustomerClient : System.ServiceModel.ClientBase<WCFServicesTest.CustomersWS.IServiceCustomer>, WCFServicesTest.CustomersWS.IServiceCustomer {
        
        public ServiceCustomerClient() {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServicesTest.CustomersWS.customers[] getcustomers() {
            return base.Channel.getcustomers();
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.CustomersWS.customers[]> getcustomersAsync() {
            return base.Channel.getcustomersAsync();
        }
        
        public bool insertcustomer(WCFServicesTest.CustomersWS.customers objcustomer) {
            return base.Channel.insertcustomer(objcustomer);
        }
        
        public System.Threading.Tasks.Task<bool> insertcustomerAsync(WCFServicesTest.CustomersWS.customers objcustomer) {
            return base.Channel.insertcustomerAsync(objcustomer);
        }
        
        public bool updatecustomer(WCFServicesTest.CustomersWS.customers objcustomer) {
            return base.Channel.updatecustomer(objcustomer);
        }
        
        public System.Threading.Tasks.Task<bool> updatecustomerAsync(WCFServicesTest.CustomersWS.customers objcustomer) {
            return base.Channel.updatecustomerAsync(objcustomer);
        }
        
        public bool deletecustomer(int id) {
            return base.Channel.deletecustomer(id);
        }
        
        public System.Threading.Tasks.Task<bool> deletecustomerAsync(int id) {
            return base.Channel.deletecustomerAsync(id);
        }
        
        public WCFServicesTest.CustomersWS.customers getcustomerById(int id) {
            return base.Channel.getcustomerById(id);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.CustomersWS.customers> getcustomerByIdAsync(int id) {
            return base.Channel.getcustomerByIdAsync(id);
        }
        
        public WCFServicesTest.CustomersWS.customers getcustomerLogin(string email, string password) {
            return base.Channel.getcustomerLogin(email, password);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.CustomersWS.customers> getcustomerLoginAsync(string email, string password) {
            return base.Channel.getcustomerLoginAsync(email, password);
        }
    }
}
