//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServicesTest.LocalsWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="locals", Namespace="http://schemas.datacontract.org/2004/07/wcf_fullcarwash")]
    [System.SerializableAttribute()]
    public partial class locals : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string schedulesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string schedules {
            get {
                return this.schedulesField;
            }
            set {
                if ((object.ReferenceEquals(this.schedulesField, value) != true)) {
                    this.schedulesField = value;
                    this.RaisePropertyChanged("schedules");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalsWS.IServiceLocal")]
    public interface IServiceLocal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/getlocals", ReplyAction="http://tempuri.org/IServiceLocal/getlocalsResponse")]
        WCFServicesTest.LocalsWS.locals[] getlocals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/getlocals", ReplyAction="http://tempuri.org/IServiceLocal/getlocalsResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.LocalsWS.locals[]> getlocalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/insertlocal", ReplyAction="http://tempuri.org/IServiceLocal/insertlocalResponse")]
        bool insertlocal(WCFServicesTest.LocalsWS.locals objloc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/insertlocal", ReplyAction="http://tempuri.org/IServiceLocal/insertlocalResponse")]
        System.Threading.Tasks.Task<bool> insertlocalAsync(WCFServicesTest.LocalsWS.locals objloc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/updatelocal", ReplyAction="http://tempuri.org/IServiceLocal/updatelocalResponse")]
        bool updatelocal(WCFServicesTest.LocalsWS.locals objlocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/updatelocal", ReplyAction="http://tempuri.org/IServiceLocal/updatelocalResponse")]
        System.Threading.Tasks.Task<bool> updatelocalAsync(WCFServicesTest.LocalsWS.locals objlocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/deletelocal", ReplyAction="http://tempuri.org/IServiceLocal/deletelocalResponse")]
        bool deletelocal(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/deletelocal", ReplyAction="http://tempuri.org/IServiceLocal/deletelocalResponse")]
        System.Threading.Tasks.Task<bool> deletelocalAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/getlocalById", ReplyAction="http://tempuri.org/IServiceLocal/getlocalByIdResponse")]
        WCFServicesTest.LocalsWS.locals getlocalById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLocal/getlocalById", ReplyAction="http://tempuri.org/IServiceLocal/getlocalByIdResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.LocalsWS.locals> getlocalByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLocalChannel : WCFServicesTest.LocalsWS.IServiceLocal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLocalClient : System.ServiceModel.ClientBase<WCFServicesTest.LocalsWS.IServiceLocal>, WCFServicesTest.LocalsWS.IServiceLocal {
        
        public ServiceLocalClient() {
        }
        
        public ServiceLocalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLocalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLocalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLocalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServicesTest.LocalsWS.locals[] getlocals() {
            return base.Channel.getlocals();
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.LocalsWS.locals[]> getlocalsAsync() {
            return base.Channel.getlocalsAsync();
        }
        
        public bool insertlocal(WCFServicesTest.LocalsWS.locals objloc) {
            return base.Channel.insertlocal(objloc);
        }
        
        public System.Threading.Tasks.Task<bool> insertlocalAsync(WCFServicesTest.LocalsWS.locals objloc) {
            return base.Channel.insertlocalAsync(objloc);
        }
        
        public bool updatelocal(WCFServicesTest.LocalsWS.locals objlocal) {
            return base.Channel.updatelocal(objlocal);
        }
        
        public System.Threading.Tasks.Task<bool> updatelocalAsync(WCFServicesTest.LocalsWS.locals objlocal) {
            return base.Channel.updatelocalAsync(objlocal);
        }
        
        public bool deletelocal(int id) {
            return base.Channel.deletelocal(id);
        }
        
        public System.Threading.Tasks.Task<bool> deletelocalAsync(int id) {
            return base.Channel.deletelocalAsync(id);
        }
        
        public WCFServicesTest.LocalsWS.locals getlocalById(int id) {
            return base.Channel.getlocalById(id);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.LocalsWS.locals> getlocalByIdAsync(int id) {
            return base.Channel.getlocalByIdAsync(id);
        }
    }
}
