//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServicesTest.ReservationsWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reservation", Namespace="http://schemas.datacontract.org/2004/07/wcf_fullcarwash")]
    [System.SerializableAttribute()]
    public partial class reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameLocalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer {
            get {
                return this.idCustomerField;
            }
            set {
                if ((this.idCustomerField.Equals(value) != true)) {
                    this.idCustomerField = value;
                    this.RaisePropertyChanged("idCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmployee {
            get {
                return this.idEmployeeField;
            }
            set {
                if ((this.idEmployeeField.Equals(value) != true)) {
                    this.idEmployeeField = value;
                    this.RaisePropertyChanged("idEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLocal {
            get {
                return this.idLocalField;
            }
            set {
                if ((this.idLocalField.Equals(value) != true)) {
                    this.idLocalField = value;
                    this.RaisePropertyChanged("idLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameCustomer {
            get {
                return this.nameCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.nameCustomerField, value) != true)) {
                    this.nameCustomerField = value;
                    this.RaisePropertyChanged("nameCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameEmployee {
            get {
                return this.nameEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.nameEmployeeField, value) != true)) {
                    this.nameEmployeeField = value;
                    this.RaisePropertyChanged("nameEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameLocal {
            get {
                return this.nameLocalField;
            }
            set {
                if ((object.ReferenceEquals(this.nameLocalField, value) != true)) {
                    this.nameLocalField = value;
                    this.RaisePropertyChanged("nameLocal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationsWS.IServiceReservations")]
    public interface IServiceReservations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/getreservations", ReplyAction="http://tempuri.org/IServiceReservations/getreservationsResponse")]
        WCFServicesTest.ReservationsWS.reservation[] getreservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/getreservations", ReplyAction="http://tempuri.org/IServiceReservations/getreservationsResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.ReservationsWS.reservation[]> getreservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/insertreservation", ReplyAction="http://tempuri.org/IServiceReservations/insertreservationResponse")]
        bool insertreservation(WCFServicesTest.ReservationsWS.reservation objreserv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/insertreservation", ReplyAction="http://tempuri.org/IServiceReservations/insertreservationResponse")]
        System.Threading.Tasks.Task<bool> insertreservationAsync(WCFServicesTest.ReservationsWS.reservation objreserv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/updatereservation", ReplyAction="http://tempuri.org/IServiceReservations/updatereservationResponse")]
        bool updatereservation(WCFServicesTest.ReservationsWS.reservation objreserv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/updatereservation", ReplyAction="http://tempuri.org/IServiceReservations/updatereservationResponse")]
        System.Threading.Tasks.Task<bool> updatereservationAsync(WCFServicesTest.ReservationsWS.reservation objreserv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/deletereservation", ReplyAction="http://tempuri.org/IServiceReservations/deletereservationResponse")]
        bool deletereservation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/deletereservation", ReplyAction="http://tempuri.org/IServiceReservations/deletereservationResponse")]
        System.Threading.Tasks.Task<bool> deletereservationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/getreservationById", ReplyAction="http://tempuri.org/IServiceReservations/getreservationByIdResponse")]
        WCFServicesTest.ReservationsWS.reservation getreservationById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReservations/getreservationById", ReplyAction="http://tempuri.org/IServiceReservations/getreservationByIdResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.ReservationsWS.reservation> getreservationByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceReservationsChannel : WCFServicesTest.ReservationsWS.IServiceReservations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceReservationsClient : System.ServiceModel.ClientBase<WCFServicesTest.ReservationsWS.IServiceReservations>, WCFServicesTest.ReservationsWS.IServiceReservations {
        
        public ServiceReservationsClient() {
        }
        
        public ServiceReservationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceReservationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReservationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReservationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServicesTest.ReservationsWS.reservation[] getreservations() {
            return base.Channel.getreservations();
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.ReservationsWS.reservation[]> getreservationsAsync() {
            return base.Channel.getreservationsAsync();
        }
        
        public bool insertreservation(WCFServicesTest.ReservationsWS.reservation objreserv) {
            return base.Channel.insertreservation(objreserv);
        }
        
        public System.Threading.Tasks.Task<bool> insertreservationAsync(WCFServicesTest.ReservationsWS.reservation objreserv) {
            return base.Channel.insertreservationAsync(objreserv);
        }
        
        public bool updatereservation(WCFServicesTest.ReservationsWS.reservation objreserv) {
            return base.Channel.updatereservation(objreserv);
        }
        
        public System.Threading.Tasks.Task<bool> updatereservationAsync(WCFServicesTest.ReservationsWS.reservation objreserv) {
            return base.Channel.updatereservationAsync(objreserv);
        }
        
        public bool deletereservation(int id) {
            return base.Channel.deletereservation(id);
        }
        
        public System.Threading.Tasks.Task<bool> deletereservationAsync(int id) {
            return base.Channel.deletereservationAsync(id);
        }
        
        public WCFServicesTest.ReservationsWS.reservation getreservationById(int id) {
            return base.Channel.getreservationById(id);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.ReservationsWS.reservation> getreservationByIdAsync(int id) {
            return base.Channel.getreservationByIdAsync(id);
        }
    }
}
