//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_fullcarwash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.DetailReservation = new HashSet<DetailReservation>();
        }
    
        public int idReservation { get; set; }
        public int idEmployee { get; set; }
        public int idCustomer { get; set; }
        public Nullable<int> idLocal { get; set; }
    
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailReservation> DetailReservation { get; set; }
        public virtual DetailReservation DetailReservation1 { get; set; }
        public virtual DetailReservation DetailReservation2 { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Local Local { get; set; }
    }
}
