//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServicesTest.DetailReservationsWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="detailreservation", Namespace="http://schemas.datacontract.org/2004/07/wcf_fullcarwash")]
    [System.SerializableAttribute()]
    public partial class detailreservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double fullpaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idcarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idreservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idserviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceserviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pricetypecarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carRegistration {
            get {
                return this.carRegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.carRegistrationField, value) != true)) {
                    this.carRegistrationField = value;
                    this.RaisePropertyChanged("carRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fullpayment {
            get {
                return this.fullpaymentField;
            }
            set {
                if ((this.fullpaymentField.Equals(value) != true)) {
                    this.fullpaymentField = value;
                    this.RaisePropertyChanged("fullpayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcar {
            get {
                return this.idcarField;
            }
            set {
                if ((this.idcarField.Equals(value) != true)) {
                    this.idcarField = value;
                    this.RaisePropertyChanged("idcar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idreservation {
            get {
                return this.idreservationField;
            }
            set {
                if ((this.idreservationField.Equals(value) != true)) {
                    this.idreservationField = value;
                    this.RaisePropertyChanged("idreservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idservice {
            get {
                return this.idserviceField;
            }
            set {
                if ((this.idserviceField.Equals(value) != true)) {
                    this.idserviceField = value;
                    this.RaisePropertyChanged("idservice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameService {
            get {
                return this.nameServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.nameServiceField, value) != true)) {
                    this.nameServiceField = value;
                    this.RaisePropertyChanged("nameService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double priceservice {
            get {
                return this.priceserviceField;
            }
            set {
                if ((this.priceserviceField.Equals(value) != true)) {
                    this.priceserviceField = value;
                    this.RaisePropertyChanged("priceservice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pricetypecar {
            get {
                return this.pricetypecarField;
            }
            set {
                if ((this.pricetypecarField.Equals(value) != true)) {
                    this.pricetypecarField = value;
                    this.RaisePropertyChanged("pricetypecar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DetailReservationsWS.IServiceDetailReservations")]
    public interface IServiceDetailReservations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/getdetailreservations", ReplyAction="http://tempuri.org/IServiceDetailReservations/getdetailreservationsResponse")]
        WCFServicesTest.DetailReservationsWS.detailreservation[] getdetailreservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/getdetailreservations", ReplyAction="http://tempuri.org/IServiceDetailReservations/getdetailreservationsResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.DetailReservationsWS.detailreservation[]> getdetailreservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/insertdetailreservation", ReplyAction="http://tempuri.org/IServiceDetailReservations/insertdetailreservationResponse")]
        bool insertdetailreservation(WCFServicesTest.DetailReservationsWS.detailreservation objdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/insertdetailreservation", ReplyAction="http://tempuri.org/IServiceDetailReservations/insertdetailreservationResponse")]
        System.Threading.Tasks.Task<bool> insertdetailreservationAsync(WCFServicesTest.DetailReservationsWS.detailreservation objdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/updatedetailreservation", ReplyAction="http://tempuri.org/IServiceDetailReservations/updatedetailreservationResponse")]
        bool updatedetailreservation(WCFServicesTest.DetailReservationsWS.detailreservation objdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/updatedetailreservation", ReplyAction="http://tempuri.org/IServiceDetailReservations/updatedetailreservationResponse")]
        System.Threading.Tasks.Task<bool> updatedetailreservationAsync(WCFServicesTest.DetailReservationsWS.detailreservation objdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/deletedetailreservation", ReplyAction="http://tempuri.org/IServiceDetailReservations/deletedetailreservationResponse")]
        bool deletedetailreservation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/deletedetailreservation", ReplyAction="http://tempuri.org/IServiceDetailReservations/deletedetailreservationResponse")]
        System.Threading.Tasks.Task<bool> deletedetailreservationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/getdetailreservationById", ReplyAction="http://tempuri.org/IServiceDetailReservations/getdetailreservationByIdResponse")]
        WCFServicesTest.DetailReservationsWS.detailreservation getdetailreservationById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDetailReservations/getdetailreservationById", ReplyAction="http://tempuri.org/IServiceDetailReservations/getdetailreservationByIdResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.DetailReservationsWS.detailreservation> getdetailreservationByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDetailReservationsChannel : WCFServicesTest.DetailReservationsWS.IServiceDetailReservations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDetailReservationsClient : System.ServiceModel.ClientBase<WCFServicesTest.DetailReservationsWS.IServiceDetailReservations>, WCFServicesTest.DetailReservationsWS.IServiceDetailReservations {
        
        public ServiceDetailReservationsClient() {
        }
        
        public ServiceDetailReservationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDetailReservationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDetailReservationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDetailReservationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServicesTest.DetailReservationsWS.detailreservation[] getdetailreservations() {
            return base.Channel.getdetailreservations();
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.DetailReservationsWS.detailreservation[]> getdetailreservationsAsync() {
            return base.Channel.getdetailreservationsAsync();
        }
        
        public bool insertdetailreservation(WCFServicesTest.DetailReservationsWS.detailreservation objdetail) {
            return base.Channel.insertdetailreservation(objdetail);
        }
        
        public System.Threading.Tasks.Task<bool> insertdetailreservationAsync(WCFServicesTest.DetailReservationsWS.detailreservation objdetail) {
            return base.Channel.insertdetailreservationAsync(objdetail);
        }
        
        public bool updatedetailreservation(WCFServicesTest.DetailReservationsWS.detailreservation objdetail) {
            return base.Channel.updatedetailreservation(objdetail);
        }
        
        public System.Threading.Tasks.Task<bool> updatedetailreservationAsync(WCFServicesTest.DetailReservationsWS.detailreservation objdetail) {
            return base.Channel.updatedetailreservationAsync(objdetail);
        }
        
        public bool deletedetailreservation(int id) {
            return base.Channel.deletedetailreservation(id);
        }
        
        public System.Threading.Tasks.Task<bool> deletedetailreservationAsync(int id) {
            return base.Channel.deletedetailreservationAsync(id);
        }
        
        public WCFServicesTest.DetailReservationsWS.detailreservation getdetailreservationById(int id) {
            return base.Channel.getdetailreservationById(id);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.DetailReservationsWS.detailreservation> getdetailreservationByIdAsync(int id) {
            return base.Channel.getdetailreservationByIdAsync(id);
        }
    }
}
